apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      imagePullSecrets: 
        - name: acr-secret
      containers:
        - name: front
          image: stockapp.azurecr.io/stockapp:stockfrontv1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: BackUrl
              valueFrom:
                  configMapKeyRef:
                    name: back-configmap
                    key: back_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: LoadBalancer
  selector:
    app: front
  ports:
    - protocol: TCP
      port: 80
