version: "3.9"

services:
    stockback:
        container_name: back
        build: ./Backend/StockApi
        ports:
            - "9000:80"
        depends_on:
            - database
        
    stockfront:
        container_name: front
        build: ./Frontend/stock-chart
        ports:
            - "4200:80"
        depends_on:
            - back
            
    database:
        container_name: backdb
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
